added missing GroupDao
klikuskodilla/JDP-1912-02 pull request #9
Opened 2020-01-03 00:04 UTC by marcinsafian

2020-01-03 22:07 UTC, naros1 approved these changes

2020-01-04 18:55 UTC, klikuskodilla commented
Dlaczego metody w tym repozytorium są zakomentowane? Nie dodaje się kodu który nic nie wnosi oraz zakomentowanego, chyba że mamy postawiony konkretny cel utrzymania tego tymczasowo ale to trzeba jasno sprecyzować.

2020-01-04 18:56 UTC, klikuskodilla requested changes
Dlaczego metody w tym repozytorium są zakomentowane? Nie dodaje się kodu który nic nie wnosi oraz zakomentowanego, chyba że mamy postawiony konkretny cel utrzymania tego tymczasowo ale to trzeba jasno sprecyzować.

2020-01-04 20:36 UTC, ghost reviewed
W encji Product zostawiłbym w jej konstruktorze "Group group". Tworząc nowy produkt powinno podawać się do jakiej grupy/kategorii należy.

2020-01-04 20:58 UTC, marcinsafian commented
Faktycznie Pull całkowicie pozbawiony jest sensu. Mogę jedynie powiedzieć, że wynika to z późnej pory. W zasadzie do usunięcia.

2020-01-04 20:58 UTC, closed without merging